name: servi_drive
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  dots_indicator: ^4.0.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  responsive_sizer: ^3.3.1
  easy_localization: ^3.0.5
  shared_preferences: ^2.2.3
  flutter_fortune_wheel: ^1.2.0
  collection: ^1.18.0
  image_cropper: ^8.0.1
  http: ^1.1.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  google_maps_flutter: ^2.12.1
  slide_action: ^0.0.2
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  animated_bottom_navigation_bar: ^1.4.0
  intl_phone_number_input: ^0.7.4
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  dropdown_button2: ^2.3.9
  dynamic_height_grid_view: ^0.0.4
  flash: ^3.1.1
  package_info_plus: ^8.0.2
  image_picker: ^1.1.2
  dotted_button: ^0.0.2
  pinput: ^4.0.0
  file_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.otf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

